DROP TABLE IF EXISTS languages;
CREATE TABLE languages (
	id int NOT NULL auto_increment,
	code varchar(8) NOT NULL,
	country varchar(128) NOT NULL,
	language varchar(128) NOT NULL,
	main bit NOT NULL,
	PRIMARY KEY(id)
);
CREATE INDEX IDX_LANGUAGES_CODE ON languages(code);
insert into languages (country, language, code, main) values ("Afghanistan", "Dari", "prs-AF",true);
insert into languages (country, language, code, main) values ("Afghanistan", "Pashto", "ps-AF",true);
insert into languages (country, language, code, main) values ("Albania", "Albanian", "sq-AL",true);
insert into languages (country, language, code, main) values ("Algeria", "Arabic", "ar-DZ",false);
insert into languages (country, language, code, main) values ("Algeria", "Tamazight", "tzm-DZ",true);
insert into languages (country, language, code, main) values ("Argentina", "Spanish", "es-AR",false);
insert into languages (country, language, code, main) values ("Armenia", "Armenian", "hy-AM",true);
insert into languages (country, language, code, main) values ("Australia", "English", "en-AU",false);
insert into languages (country, language, code, main) values ("Austria", "German", "de-AT",false);
insert into languages (country, language, code, main) values ("Azerbaijan", "Azeri", "az-AZ",true);
insert into languages (country, language, code, main) values ("Bahrain", "Arabic", "ar-BH",false);
insert into languages (country, language, code, main) values ("Bangladesh", "Bengali", "bn-BD",true);
insert into languages (country, language, code, main) values ("Belarus", "Belarusian", "be-BY",true);
insert into languages (country, language, code, main) values ("Belgium", "Dutch", "nl-BE",false);
insert into languages (country, language, code, main) values ("Belgium", "French", "fr-BE",false);
insert into languages (country, language, code, main) values ("Belize", "English", "en-BZ",false);
insert into languages (country, language, code, main) values ("Venezuela", "Spanish", "es-VE",false);
insert into languages (country, language, code, main) values ("Bolivia", "Quechua", "quz-BO",true);
insert into languages (country, language, code, main) values ("Bolivia", "Spanish", "es-BO",false);
insert into languages (country, language, code, main) values ("Bosnia and Herzegovina", "Bosnian", "bs-BA",true);
insert into languages (country, language, code, main) values ("Bosnia and Herzegovina", "Croatian", "hr-BA",false);
insert into languages (country, language, code, main) values ("Bosnia and Herzegovina", "Serbian", "sr-BA",false);
insert into languages (country, language, code, main) values ("Brazil", "Portuguese", "pt-BR",false);
insert into languages (country, language, code, main) values ("Brunei Darussalam", "Malay", "ms-BN",false);
insert into languages (country, language, code, main) values ("Bulgaria", "Bulgarian", "bg-BG",true);
insert into languages (country, language, code, main) values ("Cambodia", "Khmer", "km-KH",true);
insert into languages (country, language, code, main) values ("Canada", "English", "en-CA",false);
insert into languages (country, language, code, main) values ("Canada", "French", "fr-CA",false);
insert into languages (country, language, code, main) values ("Canada", "Inuktitut", "iu-CA",true);
insert into languages (country, language, code, main) values ("Canada", "Mohawk", "moh-CA",true);
insert into languages (country, language, code, main) values ("Caribbean", "English", "en-029",false);
insert into languages (country, language, code, main) values ("Chile", "Mapudungun", "arn-CL",true);
insert into languages (country, language, code, main) values ("Chile", "Spanish", "es-CL",false);
insert into languages (country, language, code, main) values ("Colombia", "Spanish", "es-CO",false);
insert into languages (country, language, code, main) values ("Costa Rica", "Spanish", "es-CR",false);
insert into languages (country, language, code, main) values ("Croatia", "Croatian", "hr-HR",true);
insert into languages (country, language, code, main) values ("Czech Republic", "Czech", "cs-CZ",true);
insert into languages (country, language, code, main) values ("Denmark", "Danish", "da-DK",true);
insert into languages (country, language, code, main) values ("Dominican Republic", "Spanish", "es-DO",false);
insert into languages (country, language, code, main) values ("Ecuador", "Quechua", "quz-EC",false);
insert into languages (country, language, code, main) values ("Ecuador", "Spanish", "es-EC",false);
insert into languages (country, language, code, main) values ("Egypt", "Arabic", "ar-EG",false);
insert into languages (country, language, code, main) values ("El Salvador", "Spanish", "es-SV",false);
insert into languages (country, language, code, main) values ("Estonia", "Estonian", "et-EE",true);
insert into languages (country, language, code, main) values ("Ethiopia", "Amharic", "am-ET",true);
insert into languages (country, language, code, main) values ("Faroe Islands", "Faroese", "fo-FO",true);
insert into languages (country, language, code, main) values ("Finland", "Finnish", "fi-FI",true);
insert into languages (country, language, code, main) values ("Finland", "Sami/Inari", "smn-FI",true);
insert into languages (country, language, code, main) values ("Finland", "Sami/Northern", "se-FI",false);
insert into languages (country, language, code, main) values ("Finland", "Sami/Skolt", "sms-FI",true);
insert into languages (country, language, code, main) values ("Finland", "Swedish", "sv-FI",true);
insert into languages (country, language, code, main) values ("France", "Alsatian", "gsw-FR",true);
insert into languages (country, language, code, main) values ("France", "Breton", "br-FR",true);
insert into languages (country, language, code, main) values ("France", "Corsican", "co-FR",true);
insert into languages (country, language, code, main) values ("France", "French", "fr-FR",true);
insert into languages (country, language, code, main) values ("France", "Occitan", "oc-FR",true);
insert into languages (country, language, code, main) values ("Georgia", "Georgian", "ka-GE",true);
insert into languages (country, language, code, main) values ("Germany", "German", "de-DE",true);
insert into languages (country, language, code, main) values ("Germany", "Lower Sorbian", "dsb-DE",true);
insert into languages (country, language, code, main) values ("Germany", "Upper Sorbian", "hsb-DE",true);
insert into languages (country, language, code, main) values ("Greece", "Greek", "el-GR",true);
insert into languages (country, language, code, main) values ("Greenland", "Greenlandic", "kl-GL",true);
insert into languages (country, language, code, main) values ("Guatemala", "Kiche", "qut-GT",true);
insert into languages (country, language, code, main) values ("Guatemala", "Spanish", "es-GT",false);
insert into languages (country, language, code, main) values ("Honduras", "Spanish", "es-HN",false);
insert into languages (country, language, code, main) values ("Hong Kong", "Chinese/Trad.", "zh-HK",false);
insert into languages (country, language, code, main) values ("Hungary", "Hungarian", "hu-HU",true);
insert into languages (country, language, code, main) values ("Iceland", "Icelandic", "is-IS",true);
insert into languages (country, language, code, main) values ("India", "Assamese", "as-IN",true);
insert into languages (country, language, code, main) values ("India", "Bengali", "bn-IN",false);
insert into languages (country, language, code, main) values ("India", "English", "en-IN",false);
insert into languages (country, language, code, main) values ("India", "Gujarati", "gu-IN",true);
insert into languages (country, language, code, main) values ("India", "Hindi", "hi-IN",true);
insert into languages (country, language, code, main) values ("India", "Kannada", "kn-IN",true);
insert into languages (country, language, code, main) values ("India", "Konkani", "kok-IN",true);
insert into languages (country, language, code, main) values ("India", "Malayalam", "ml-IN",true);
insert into languages (country, language, code, main) values ("India", "Marathi", "mr-IN",true);
insert into languages (country, language, code, main) values ("India", "Oriya", "or-IN",true);
insert into languages (country, language, code, main) values ("India", "Punjabi", "pa-IN",true);
insert into languages (country, language, code, main) values ("India", "Sanskrit", "sa-IN",true);
insert into languages (country, language, code, main) values ("India", "Tamil", "ta-IN",true);
insert into languages (country, language, code, main) values ("India", "Telugu", "te-IN",true);
insert into languages (country, language, code, main) values ("Indonesia", "Indonesian", "id-ID",true);
insert into languages (country, language, code, main) values ("Iran", "Persian", "fa-IR",true);
insert into languages (country, language, code, main) values ("Iraq", "Arabic", "ar-IQ",false);
insert into languages (country, language, code, main) values ("Ireland", "English", "en-IE",false);
insert into languages (country, language, code, main) values ("Ireland", "Irish", "ga-IE",true);
insert into languages (country, language, code, main) values ("Pakistan", "Urdu", "ur-PK",true);
insert into languages (country, language, code, main) values ("Israel", "Hebrew", "he-IL",true);
insert into languages (country, language, code, main) values ("Italy", "Italian", "it-IT",true);
insert into languages (country, language, code, main) values ("Jamaica", "English", "en-JM",false);
insert into languages (country, language, code, main) values ("Japan", "Japanese", "ja-JP",true);
insert into languages (country, language, code, main) values ("Jordan", "Arabic", "ar-JO",false);
insert into languages (country, language, code, main) values ("Kazakhstan", "Kazakh", "kk-KZ",true);
insert into languages (country, language, code, main) values ("Kenya", "Kiswahili", "sw-KE",true);
insert into languages (country, language, code, main) values ("Korea", "Korean", "ko-KR",true);
insert into languages (country, language, code, main) values ("Kuwait", "Arabic", "ar-KW",false);
insert into languages (country, language, code, main) values ("Kyrgyzstan", "Kyrgyz", "ky-KG",true);
insert into languages (country, language, code, main) values ("Lao P.D.R.", "Lao", "lo-LA",true);
insert into languages (country, language, code, main) values ("Latvia", "Latvian", "lv-LV",true);
insert into languages (country, language, code, main) values ("Lebanon", "Arabic", "ar-LB",false);
insert into languages (country, language, code, main) values ("Libya", "Arabic", "ar-LY",false);
insert into languages (country, language, code, main) values ("Liechtenstein", "German", "de-LI",false);
insert into languages (country, language, code, main) values ("Lithuania", "Lithuanian", "lt-LT",true);
insert into languages (country, language, code, main) values ("Luxembourg", "French", "fr-LU",false);
insert into languages (country, language, code, main) values ("Luxembourg", "German", "de-LU",false);
insert into languages (country, language, code, main) values ("Luxembourg", "Luxembourgish", "lb-LU",true);
insert into languages (country, language, code, main) values ("Macao S.A.R.", "Chinese/Trad.", "zh-MO",false);
insert into languages (country, language, code, main) values ("Macedonia (FYROM)", "Macedonian", "mk-MK",true);
insert into languages (country, language, code, main) values ("Malaysia", "English", "en-MY",false);
insert into languages (country, language, code, main) values ("Malaysia", "Malay", "ms-MY",true);
insert into languages (country, language, code, main) values ("Maldives", "Divehi", "dv-MV",true);
insert into languages (country, language, code, main) values ("Malta", "Maltese", "mt-MT",true);
insert into languages (country, language, code, main) values ("Mexico", "Spanish", "es-MX",false);
insert into languages (country, language, code, main) values ("Mongolia", "Mongolian", "mn-MN",true);
insert into languages (country, language, code, main) values ("Montenegro", "Serbian", "sr-ME",false);
insert into languages (country, language, code, main) values ("Morocco", "Arabic", "ar-MA",false);
insert into languages (country, language, code, main) values ("Nepal", "Nepali", "ne-NP",true);
insert into languages (country, language, code, main) values ("Netherlands", "Dutch", "nl-NL",true);
insert into languages (country, language, code, main) values ("Netherlands", "Frisian", "fy-NL",true);
insert into languages (country, language, code, main) values ("New Zealand", "English", "en-NZ",false);
insert into languages (country, language, code, main) values ("New Zealand", "Maori", "mi-NZ",true);
insert into languages (country, language, code, main) values ("Nicaragua", "Spanish", "es-NI",false);
insert into languages (country, language, code, main) values ("Nigeria", "Hausa", "ha-NG",true);
insert into languages (country, language, code, main) values ("Nigeria", "Igbo", "ig-NG",true);
insert into languages (country, language, code, main) values ("Nigeria", "Yoruba", "yo-NG",true);
insert into languages (country, language, code, main) values ("Norway", "Norwegian/Bokmal", "nb-NO",true);
insert into languages (country, language, code, main) values ("Norway", "Norwegian/Nynorsk", "nn-NO",true);
insert into languages (country, language, code, main) values ("Norway", "Sami/Lule", "smj-NO",false);
insert into languages (country, language, code, main) values ("Norway", "Sami/Northern", "se-NO",true);
insert into languages (country, language, code, main) values ("Norway", "Sami/Southern", "sma-NO",false);
insert into languages (country, language, code, main) values ("Oman", "Arabic", "ar-OM",false);
insert into languages (country, language, code, main) values ("Panama", "Spanish", "es-PA",false);
insert into languages (country, language, code, main) values ("Paraguay", "Spanish", "es-PY",false);
insert into languages (country, language, code, main) values ("P.R. China", "Chinese/Simpl.", "zh-CN",true);
insert into languages (country, language, code, main) values ("P.R. China", "Mongolian/Trad.", "mn-CN",true);
insert into languages (country, language, code, main) values ("P.R. China", "Tibetan", "bo-CN",true);
insert into languages (country, language, code, main) values ("P.R. China", "Uyghur", "ug-CN",true);
insert into languages (country, language, code, main) values ("P.R. China", "Yi", "ii-CN",true);
insert into languages (country, language, code, main) values ("Peru", "Quechua", "quz-PE",true);
insert into languages (country, language, code, main) values ("Peru", "Spanish", "es-PE",false);
insert into languages (country, language, code, main) values ("Philippines", "Filipino", "fil-PH",true);
insert into languages (country, language, code, main) values ("Poland", "Polish", "pl-PL",true);
insert into languages (country, language, code, main) values ("Portugal", "Portuguese", "pt-PT",true);
insert into languages (country, language, code, main) values ("Principality of Monaco", "French", "fr-MC",false);
insert into languages (country, language, code, main) values ("Puerto Rico", "Spanish", "es-PR",false);
insert into languages (country, language, code, main) values ("Qatar", "Arabic", "ar-QA",false);
insert into languages (country, language, code, main) values ("Philippines", "English", "en-PH",false);
insert into languages (country, language, code, main) values ("Romania", "Romanian", "ro-RO",true);
insert into languages (country, language, code, main) values ("Russia", "Bashkir", "ba-RU",true);
insert into languages (country, language, code, main) values ("Russia", "Russian", "ru-RU",true);
insert into languages (country, language, code, main) values ("Russia", "Tatar", "tt-RU",true);
insert into languages (country, language, code, main) values ("Russia", "Yakut", "sah-RU",true);
insert into languages (country, language, code, main) values ("Rwanda", "Kinyarwanda", "rw-RW",true);
insert into languages (country, language, code, main) values ("Saudi Arabia", "Arabic", "ar-SA",true);
insert into languages (country, language, code, main) values ("Senegal", "Wolof", "wo-SN",true);
insert into languages (country, language, code, main) values ("Serbia", "Serbian", "sr-RS",true);
insert into languages (country, language, code, main) values ("Serbia and Montenegro (Former)", "Serbian", "sr-CS",false);
insert into languages (country, language, code, main) values ("Singapore", "Chinese/Simpl.", "zh-SG",false);
insert into languages (country, language, code, main) values ("Singapore", "English", "en-SG",false);
insert into languages (country, language, code, main) values ("Slovakia", "Slovak", "sk-SK",true);
insert into languages (country, language, code, main) values ("Slovenia", "Slovenian", "sl-SI",true);
insert into languages (country, language, code, main) values ("South Africa", "Afrikaans", "af-ZA",true);
insert into languages (country, language, code, main) values ("South Africa", "English", "en-ZA",false);
insert into languages (country, language, code, main) values ("South Africa", "Xhosa", "xh-ZA",true);
insert into languages (country, language, code, main) values ("South Africa", "Zulu", "zu-ZA",true);
insert into languages (country, language, code, main) values ("South Africa", "Sesotho sa Leboa", "nso-ZA",true);
insert into languages (country, language, code, main) values ("South Africa", "Setswana", "tn-ZA",true);
insert into languages (country, language, code, main) values ("Spain", "Basque", "eu-ES",true);
insert into languages (country, language, code, main) values ("Spain", "Catalan", "ca-ES",true);
insert into languages (country, language, code, main) values ("Spain", "Galician", "gl-ES",true);
insert into languages (country, language, code, main) values ("Spain", "Spanish", "es-ES",true);
insert into languages (country, language, code, main) values ("Sri Lanka", "Sinhala", "si-LK",true);
insert into languages (country, language, code, main) values ("Sweden", "Sami/Lule", "smj-SE",true);
insert into languages (country, language, code, main) values ("Sweden", "Sami/Northern", "se-SE",false);
insert into languages (country, language, code, main) values ("Sweden", "Sami/Southern", "sma-SE",true);
insert into languages (country, language, code, main) values ("Sweden", "Swedish", "sv-SE",true);
insert into languages (country, language, code, main) values ("Switzerland", "French", "fr-CH",false);
insert into languages (country, language, code, main) values ("Switzerland", "German", "de-CH",false);
insert into languages (country, language, code, main) values ("Switzerland", "Italian", "it-CH",false);
insert into languages (country, language, code, main) values ("Switzerland", "Romansh", "rm-CH",true);
insert into languages (country, language, code, main) values ("Syria", "Arabic", "ar-SY",false);
insert into languages (country, language, code, main) values ("Syria", "Syriac", "syr-SY",true);
insert into languages (country, language, code, main) values ("Taiwan", "Chinese/Trad.", "zh-TW",false);
insert into languages (country, language, code, main) values ("Tajikistan", "Tajik", "tg-TJ",true);
insert into languages (country, language, code, main) values ("Thailand", "Thai", "th-TH",true);
insert into languages (country, language, code, main) values ("Trinidad and Tobago", "English", "en-TT",false);
insert into languages (country, language, code, main) values ("Tunisia", "Arabic", "ar-TN",false);
insert into languages (country, language, code, main) values ("Turkey", "Turkish", "tr-TR",true);
insert into languages (country, language, code, main) values ("Turkmenistan", "Turkmen", "tk-TM",true);
insert into languages (country, language, code, main) values ("U.A.E.", "Arabic", "ar-AE",false);
insert into languages (country, language, code, main) values ("Ukraine", "Ukrainian", "uk-UA",true);
insert into languages (country, language, code, main) values ("United Kingdom", "English", "en-GB",true);
insert into languages (country, language, code, main) values ("United Kingdom", "Scottish Gaelic", "gd-GB",true);
insert into languages (country, language, code, main) values ("United Kingdom", "Welsh", "cy-GB",true);
insert into languages (country, language, code, main) values ("United States", "English", "en-US",false);
insert into languages (country, language, code, main) values ("United States", "Spanish", "es-US",false);
insert into languages (country, language, code, main) values ("Uruguay", "Spanish", "es-UY",false);
insert into languages (country, language, code, main) values ("Uzbekistan", "Uzbek", "uz-UZ",true);
insert into languages (country, language, code, main) values ("Vietnam", "Vietnamese", "vi-VN",true);
insert into languages (country, language, code, main) values ("Yemen", "Arabic", "ar-YE",false);
insert into languages (country, language, code, main) values ("Zimbabwe", "English", "en-ZW",false);
